spring.application.name=SmartPoolGuardian
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=postgresql://smartpoolguardian_user:cXSUEKEcPfYs1BJNuJuZCFFRHyi94mKI@dpg-d80fes9o3t8c73dnimlg-a.oregon-postgres.render.com/smartpoolguardian
spring.datasource.username=smartpoolguardian_user
spring.datasource.password=cXSUEKEcPfYs1BJNuJuZCFFRHyi94mKI
spring.profiles.active=local
server.port=${PORT:8080}
