spring.application.name=SmartPoolGuardian
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/SMARTPOOLGUARDIAN
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.profiles.active=local
spring.profiles.include=local
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.api.key=${GEMINI_API_KEY}