spring.application.name=SmartPoolGuardian
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/SMARTPOOLGUARDIAN
<<<<<<< HEAD

spring.datasource.username=postgres
spring.datasource.password=postgre

=======
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
>>>>>>> 4577b41c06bec77f064e708bab4b4aac95dda829
spring.profiles.active=local